// TURN/STUN for peer-to-peer clients: the ICE servers DUB hands out with its credentials,
// the eturnal config that serves them, and the nginx stream block that exposes TLS.
// See docs/TURN.md.
//
// Pure: callers pass in the base URL and listen address, the two facts that differ per
// environment.

import { TURN_REALM } from './dub.js';
import type { NetworkDef } from './networks.js';
import { requiredPort } from './toml-generator.js';

/** The relay rides DUB, which rides People Chain: the same gate the spawn applies. */
export function runsTurnRelay(net: NetworkDef): boolean {
  return (
    net.parachains.some((p) => p.key === 'people') &&
    net.services['dub'] !== false &&
    net.services['turn'] !== false
  );
}

/**
 * Local-only secret. turn-api reads TURN_SECRET as base64 and keys the HMAC with the decoded
 * bytes, while eturnal keys it with its secret string as-is, so the decoded value must be a
 * printable string for the two to agree.
 */
export const LOCAL_TURN_SECRET = Buffer.from('ppn-local-turn-secret').toString('base64');

export interface TurnPorts {
  /** UDP and TCP, straight from clients. */
  listen: number;
  /** nginx terminates TLS here (servers only). */
  tls: number;
  /** Loopback TCP with the PROXY protocol, nginx's upstream. */
  proxy: number;
  relayMin: number;
  relayMax: number;
}

export function turnPorts(): TurnPorts {
  return {
    listen: requiredPort('TURN_PORT'),
    tls: requiredPort('TURN_TLS_PORT'),
    proxy: requiredPort('TURN_PROXY_PORT'),
    relayMin: requiredPort('TURN_RELAY_MIN_PORT'),
    relayMax: requiredPort('TURN_RELAY_MAX_PORT'),
  };
}

export interface IceServer {
  id: string;
  label: string;
  url: string;
  transport: 'udp' | 'tcp' | 'tls';
  port: number;
}

/**
 * What clients connect to, on the host the network is published under. `turns:` is offered
 * only behind https, where nginx holds a certificate for that host.
 */
export function iceServers(baseUrl: string, ports: TurnPorts = turnPorts()): IceServer[] {
  const url = new URL(baseUrl);
  const host = url.hostname;
  const servers: IceServer[] = [
    { id: 'stun', label: 'STUN', url: `stun:${host}:${ports.listen}`, transport: 'udp', port: ports.listen },
    { id: 'turn-udp', label: 'TURN (UDP)', url: `turn:${host}:${ports.listen}?transport=udp`, transport: 'udp', port: ports.listen },
    { id: 'turn-tcp', label: 'TURN (TCP)', url: `turn:${host}:${ports.listen}?transport=tcp`, transport: 'tcp', port: ports.listen },
  ];
  if (url.protocol === 'https:') {
    servers.push({ id: 'turns', label: 'TURN (TLS)', url: `turns:${host}:${ports.tls}?transport=tcp`, transport: 'tls', port: ports.tls });
  }
  return servers;
}

/**
 * TURN_SECRET as both halves need it: base64 for turn-api, decoded for eturnal. A deployment
 * (one that named a secrets file) must set its own; the local default is public.
 */
export function turnSecret(raw: string | undefined, deployed: boolean): { base64: string; plain: string } {
  if (!raw) {
    if (deployed) {
      throw new Error(
        'TURN_SECRET is not set in PPN_SECRETS_FILE. The dev default is public; a deployment\n' +
          '       must supply its own: base64 of a printable string (see docs/TURN.md).'
      );
    }
    raw = LOCAL_TURN_SECRET;
  }
  const plain = Buffer.from(raw.trim(), 'base64').toString('latin1');
  if (!plain || !/^[\x21-\x7e]+$/.test(plain) || Buffer.from(plain, 'latin1').toString('base64') !== raw.trim()) {
    throw new Error(
      'TURN_SECRET must be base64 of a printable ASCII string: eturnal uses the decoded string\n' +
        '       as its key, turn-api the decoded bytes, and they only agree when those are the same.'
    );
  }
  return { base64: raw.trim(), plain };
}

const isLoopback = (ip: string) => ip === '127.0.0.1' || ip === '::1' || ip === 'localhost';
const isIpv4 = (ip: string) => /^\d{1,3}(\.\d{1,3}){3}$/.test(ip);

/**
 * eturnal.yml. The secret is not in it: eturnal reads ETURNAL_SECRET when the file names
 * none, which keeps it off disk.
 */
export function eturnalConfig(opts: { listenIp: string; runDir: string; ports?: TurnPorts }): string {
  const ports = opts.ports ?? turnPorts();
  const ip = opts.listenIp;
  const relayAddr = isIpv4(ip) && ip !== '0.0.0.0' ? `\n  relay_ipv4_addr: "${ip}"` : '';
  // "recommended" blocks loopback, which is where every peer is on a laptop.
  const whitelist = isLoopback(ip) ? '\n  whitelist_peers:\n    - "127.0.0.1"' : '';
  return `# Generated by \`ppn service turn\`; edits are overwritten on start.
eturnal:
  realm: "${TURN_REALM}"
  listen:
    - ip: "${ip}"
      port: ${ports.listen}
      transport: udp
    - ip: "${ip}"
      port: ${ports.listen}
      transport: tcp
    - ip: "127.0.0.1"
      port: ${ports.proxy}
      transport: tcp
      proxy_protocol: true${relayAddr}
  relay_min_port: ${ports.relayMin}
  relay_max_port: ${ports.relayMax}
  blacklist_peers:
    - recommended${whitelist}
  log_dir: stdout
  log_level: info
  run_dir: "${opts.runDir}"
  modules:
    mod_log_stun: {}
`;
}

/**
 * The nginx `stream` block for `turns:`. Certificates come from the template's stream{}
 * context, which already holds them for the p2p WSS streams.
 */
export function nginxTurnStream(ports: TurnPorts = turnPorts()): string {
  return `    upstream turn_proxy {
        server 127.0.0.1:${ports.proxy};
    }

    # TURN over TLS; plain STUN/TURN on ${ports.listen} goes straight to eturnal
    server {
        listen ${ports.tls} ssl;
        proxy_pass turn_proxy;
        proxy_protocol on;
    }`;
}
