// The spawn environment `ppn start` states, in one place.
//
// zombienet forwards no environment to custom processes, so everything the dashboard,
// eth-rpc, the dub stack and the storage provider cannot derive has to be *stated*.
// `ppn start` states it twice: config/ports.local.env (read by custom processes) and
// zombie-cli's child environment (inherited by node-level processes). A server never runs
// `ppn start` — ppn.service spawns zombie-cli directly — so the same facts are restated by
// hand across server/redeploy.sh, server/systemd/ppn.service and /etc/ppn/deploy.env.
//
// This module is the canonical statement: `ppn start` builds its real environment from the
// builders below, and the key lists are derived from those same builders — so the list the
// server-side conformance test (server/tests/spawn-env-conformance.test.mjs) checks against
// cannot drift from what the code actually does.

/** Facts config/ports.local.env states for zombienet's custom processes. */
export interface LocalEnvFacts {
  /** The network this run resolved to, so every service resolves the same one. */
  network: string;
  /** The data dir this run writes to — per-mode (data/ vs data-fork/). */
  dataDir: string;
  ephemeral: boolean;
  /** Where the identity postgres cluster keeps its data. */
  identityDataDir: string;
}

/** The gitignored file `ppn start` writes; every service overlays it on top of ports.env. */
export function localEnvContent(f: LocalEnvFacts): string {
  return (
    '# Generated by `ppn start` — gitignored, do not edit.\n' +
    `WEB3_STORAGE_PROVIDER_STORAGE_MODE=${f.ephemeral ? 'inmemory' : 'disk'}\n` +
    `DUB_POSTGRES_DATA_DIR=${f.identityDataDir}\n` +
    `PPN_NETWORK=${f.network}\n` +
    // zombienet forwards no env to custom processes, and the data dir is per-mode
    // (data/ vs data-fork/): without this the dashboard reads the *other* mode's
    // spawn stamp and logs — a fork reporting itself as yesterday's genesis.
    `PPN_DATA_DIR=${f.dataDir}\n`
  );
}

/** Facts `ppn start` puts into zombie-cli's environment (inherited by node-level procs). */
export interface ChildEnvFacts {
  binDir: string;
  /** The workspace this run resolved to, so the launchers do not resolve it again. */
  workspace: string;
  scriptsDir: string;
  dataDir: string;
  ephemeral: boolean;
}

export function childEnv(f: ChildEnvFacts): Record<string, string> {
  return {
    BIN: f.binDir,
    // zombienet forwards node-level env but gives custom processes no HOME, which is the
    // one thing the shell fallback would need — so the resolved workspace travels here.
    PPN_HOME: f.workspace,
    SCRIPTS: f.scriptsDir,
    DATA_DIR: f.dataDir,
    EPHEMERAL: f.ephemeral ? '1' : '',
  };
}

const DUMMY_LOCAL: LocalEnvFacts = { network: 'x', dataDir: 'x', ephemeral: false, identityDataDir: 'x' };
const DUMMY_CHILD: ChildEnvFacts = { binDir: 'x', workspace: 'x', scriptsDir: 'x', dataDir: 'x', ephemeral: false };

/** Keys `ppn start` writes into config/ports.local.env, derived from the real writer. */
export function localEnvKeys(): string[] {
  return [...localEnvContent(DUMMY_LOCAL).matchAll(/^([A-Z_][A-Z0-9_]*)=/gm)].map((m) => m[1]);
}

/** Keys `ppn start` puts into zombie-cli's environment, derived from the real builder. */
export function childEnvKeys(): string[] {
  return Object.keys(childEnv(DUMMY_CHILD));
}

/** Every key a spawn receives through `ppn start`, deduplicated. */
export function spawnEnvKeys(): string[] {
  return [...new Set([...localEnvKeys(), ...childEnvKeys()])];
}

/**
 * Keys the server path deliberately does not supply. Each needs a reason, and the reason has
 * to be about the *server*, not about effort.
 */
export const WAIVED: Record<string, string> = {
  // A server persists by definition; ephemeral is a laptop mode. Nothing reads it there.
  EPHEMERAL: 'ephemeral is a local-only mode; a deployment always persists',

  // KNOWN GAP, deliberately recorded rather than silently waived.
  //
  // `ppn start` sets it so every service resolves the network the user asked for.
  // On a server nothing sets it, and currentNetworkName() (network-config/src/networks.ts)
  // falls back to previewnet. Staging and prod run previewnet, so this is *accidentally*
  // correct today and breaks nothing — but the first non-previewnet deployment would have
  // every service resolve previewnet's chains, ports and bin directory instead.
  //
  // Not fixed here because the fix belongs with `ppn start --server` (see docs/DASHBOARD.md,
  // "Why a server does not run `ppn start`"), which makes one path the sole author of all of
  // this. Until then it is written down, and the conformance test keeps it from being
  // forgotten.
  PPN_NETWORK: 'KNOWN GAP: falls back to previewnet, which is what servers run today',
};
